language: java
sudo: false

jdk:
- oraclejdk8

addons:
  sonarcloud:
    token:
      secure: ${SONARCLOUD_TOKEN}
      
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2"
  - '$HOME/.sonar/cache'
  
