language: java
sudo: false

jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: "csegu-github"
    token:
      secure: ${SONARCLOUD_TOKEN}
      
script:
  - mvn clean install sonar:sonar -Dsonar.projectKey=csegu_porra-futbol \
  -Dsonar.organization=csegu-github \
  -Dsonar.host.url=https://sonarcloud.io

cache:
  directories:
  - "$HOME/.m2"
  - '$HOME/.sonar/cache'
  
