language: java
sudo: false

jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: "porra-futbol-github"
    token:
      secure: ${SONARCLOUD_TOKEN}
      
script:
  - mvn clean install sonar:sonar

cache:
  directories:
  - "$HOME/.m2"
  - '$HOME/.sonar/cache'
  
